//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniLibraryMgmtSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOOK
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BOOK()
        {
            this.BOOK_ISSUE = new HashSet<BOOK_ISSUE>();
            this.BOOK_RECEIEVED = new HashSet<BOOK_RECEIEVED>();
        }
    
        public int ID { get; set; }
        public Nullable<int> BOOK_CATEGORY_ID { get; set; }
        public Nullable<int> PUBLISHER_ID { get; set; }
        public string BOOK_NAME { get; set; }
        public string BOOK_SUBJECT { get; set; }
        public string BOOK_DESCRIPTION { get; set; }
        public Nullable<int> AUTHOR_MASTER_ID { get; set; }
    
        public virtual BOOK_CATEGORY BOOK_CATEGORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOOK_ISSUE> BOOK_ISSUE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOOK_RECEIEVED> BOOK_RECEIEVED { get; set; }
        public virtual PUBLISHER PUBLISHER { get; set; }
        public virtual AUTHOR AUTHOR { get; set; }
    }
}
