//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniLibraryMgmtSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEMBER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MEMBER()
        {
            this.BOOK_ISSUE = new HashSet<BOOK_ISSUE>();
            this.BOOK_RECEIEVED = new HashSet<BOOK_RECEIEVED>();
        }
    
        public int ID { get; set; }
        public Nullable<int> MemberTypeId { get; set; }
        public string MEMBERSHIP_ID { get; set; }
        public Nullable<System.DateTime> MEMBERSHIP_DATE { get; set; }
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string ADDRESS { get; set; }
        public string EMAIL { get; set; }
        public string CONTACT_NO { get; set; }
        public string EDUCATION { get; set; }
        public string REMARKS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOOK_ISSUE> BOOK_ISSUE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOOK_RECEIEVED> BOOK_RECEIEVED { get; set; }
        public virtual MemberType MemberType { get; set; }
    }
}
